# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release Ethsential

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    strategy:
    matrix:
      node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      working-directory: server
    - name: Build and Publish App
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
      working-directory: server
    - name: Build and publish Extension
      if: success()
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: npm install
      run: npm install vsce --save-dev
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      working-directory: vscode-client
